services:
  - type: web
    name: transparent-fund-tracker-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
